const bodyMor = [
    "\n<p><strong>* Daily Guided Yoga | 1 - 31 Oct 2021 | Raipur, C.G. *</strong></p>\n\n<p>Greetings,</p>\n\n<p><br />We are very excited to have you at the upcoming <strong>Daily Guided Yoga</strong> program. Please find information you'll need below.</p>\n\n<p><strong>Program Information:</strong><br />🧘&zwj;♀️ Program Name: Daily Guided Yoga<br />📅 Program Date: Oct 1 - 31<br />🕐 Timings: 8:30 AM - 9:30 AM [<b>Exception</b> - For 4, 5 & 6 Oct timings will be from 8:00 AM to 9:30 AM]<br />🕐 Timings: ProgramTiming<br />🧘&zwj;♂️ Age: 14 years and above<br />🏡 Venue: Rotary Greater Hall, Pagaria Complex, Bus Stand, Pandri, Raipur (https://bit.ly/3BSPMI5)<br /><br />Check in: 30 minutes before session starts</p>\n\n<p>Session starts everyday <strong>SHARP</strong> on time. It's best to be seated at least 5 minutes ahead of time and let your breath and metabolism settle down. Late comers may not be allowed to participate.</p>\n\n<p><strong>General Information:</strong><br />✔️ Ensure to wear face mask, maintain social distancing, and take care of hand hygiene and respiratory etiquette at all times</p>\n\n<p>✔️ Attendance for all sessions is required</p>\n\n<p>✔️ Wear loose fitting and comfortable clothing</p>\n\n<p>✔️ Bring a yoga mat or cloth-mat to sit on</p>\n\n<p>✔️ You can bring a cushion if needed to sit comfortably on the floor</p>\n\n<p>✔️ Please allow additional time of 10-15 minutes for traffic delays, find parking and complete check-in formalities before the program begins</p>\n\n<p><span style='background-color: #ffff00;'><strong>Empty stomach condition required:</strong></span> Due to the nature of the practices, please ensure you finish any heavy meal at least 4 hours before the class, snack 2.5 hours before and beverage (except water) at least 1.5 hour before the session.</p>\n\n<p>If you have any questions feel free to contact us at <strong>contact@theclassicalyoga.com</strong> or <strong>+91 81096-96955</strong></p>\n\n<p>See you at the program!</p>\n\n<p>Warm regards,<br />The Classical Yoga Team</p>"

    , "\n<p><strong>* Bhuta Shuddhi | 8 Oct 2021 | Raipur, C.G. *</strong></p>\n<p>Greetings,<br />We are very excited to have you at the upcoming Bhuta Shuddhi program. Please find information you'll need below.</p>\n<p>Program Information:<br />🧘&zwj;♀️ Program Name: Bhuta Shuddhi<br />📅 Program Date: Oct 8<br />🕐 Timings: 7:00 AM - 8:00 AM <br />🧘&zwj;♂️ Age: 14 years and above<br />🏡 Venue: Rotary Greater Hall, Pagaria Complex<br />Bus Stand, Pandri, Raipur (https://bit.ly/3BSPMI5) <br /><br />Check in: 30 minutes before session starts</p>\n<p>Session starts everyday SHARP on time. It's best to be seated at least 5 minutes ahead of time and let your breath and metabolism settle down. Late comers may not be allowed to participate.</p>\n<p>General Information:<br />✔️ Ensure to wear face mask, maintain social distancing, and take care of hand hygiene and respiratory etiquette at all times</p>\n<p>✔️ Attendance for all sessions is required</p>\n<p>✔️ Wear loose fitting and comfortable clothing</p>\n<p>✔️ Bring a yoga mat or cloth-mat to sit on</p>\n<p>✔️ You can bring a cushion if needed to sit comfortably on the floor</p>\n<p>✔️ Please allow additional time of 10-15 minutes for traffic delays, find parking and complete check-in formalities before the program begins</p>\n<p>Empty stomach condition required: Due to the nature of the practices, please ensure you finish any heavy meal at least 4 hours before the class, snack 2.5 hours before and beverage (except water) at least 1.5 hour before the session.</p>\n<p>If you have any questions feel free to contact us at contact@theclassicalyoga.com or +91 81096-96955</p>\n<p>See you at the program!</p>\n<p>Warm regards,<br />The Classical Yoga Team</p>" 

    , "\n<p><strong>* Surya Kriya (For those who have completed Surya Shakti) | 7 Oct 2021 | Raipur, C.G. *</strong></p>\n<p>Greetings,<br />We are very excited to have you at the upcoming Surya Kriya program. Please find information you'll need below.</p>\n<p>Program Information:<br />🧘&zwj;♀️ Program Name: Surya Kriya (For those who have completed Surya Shakti)<br />📅 Program Date: Oct 7<br />🕐 Timings: 6:00 AM - 8:00 AM <br />🧘&zwj;♂️ Age: 14 years and above<br />🏡 Venue: Rotary Greater Hall, Pagaria Complex<br />Bus Stand, Pandri, Raipur (https://bit.ly/3BSPMI5) <br /><br />Check in: 30 minutes before session starts</p>\n<p>Session starts everyday SHARP on time. It's best to be seated at least 5 minutes ahead of time and let your breath and metabolism settle down. Late comers may not be allowed to participate.</p>\n<p>General Information:<br />✔️ Ensure to wear face mask, maintain social distancing, and take care of hand hygiene and respiratory etiquette at all times</p>\n<p>✔️ Attendance for all sessions is required</p>\n<p>✔️ Wear loose fitting and comfortable clothing</p>\n<p>✔️ Bring a yoga mat or cloth-mat to sit on</p>\n<p>✔️ You can bring a cushion if needed to sit comfortably on the floor</p>\n<p>✔️ Please allow additional time of 10-15 minutes for traffic delays, find parking and complete check-in formalities before the program begins</p>\n<p>Empty stomach condition required: Due to the nature of the practices, please ensure you finish any heavy meal at least 4 hours before the class, snack 2.5 hours before and beverage (except water) at least 1.5 hour before the session.</p>\n<p>If you have any questions feel free to contact us at contact@theclassicalyoga.com or +91 81096-96955</p>\n<p>See you at the program!</p>\n<p>Warm regards,<br />The Classical Yoga Team</p>"   

    , "\n<p><strong>* Surya Shakti | 4-6 Oct 2021 | Raipur, C.G. *</strong></p>\n<p>Greetings,<br />We are very excited to have you at the upcoming Surya Shakti program. Please find information you'll need below.</p>\n<p>Program Information:<br />🧘&zwj;♀️ Program Name: Surya Shakti<br />📅 Program Date: Oct 4-6<br />🕐 Timings: 8:00 AM - 9:30 AM <br />🧘&zwj;♂️ Age: 14 years and above<br />🏡 Venue: Rotary Greater Hall, Pagaria Complex<br />Bus Stand, Pandri, Raipur (https://bit.ly/3BSPMI5) <br /><br />Check in: 30 minutes before session starts</p>\n<p>Session starts everyday SHARP on time. It's best to be seated at least 5 minutes ahead of time and let your breath and metabolism settle down. Late comers may not be allowed to participate.</p>\n<p>General Information:<br />✔️ Ensure to wear face mask, maintain social distancing, and take care of hand hygiene and respiratory etiquette at all times</p>\n<p>✔️ Attendance for all sessions is required</p>\n<p>✔️ Wear loose fitting and comfortable clothing</p>\n<p>✔️ Bring a yoga mat or cloth-mat to sit on</p>\n<p>✔️ You can bring a cushion if needed to sit comfortably on the floor</p>\n<p>✔️ Please allow additional time of 10-15 minutes for traffic delays, find parking and complete check-in formalities before the program begins</p>\n<p>Empty stomach condition required: Due to the nature of the practices, please ensure you finish any heavy meal at least 4 hours before the class, snack 2.5 hours before and beverage (except water) at least 1.5 hour before the session.</p>\n<p>If you have any questions feel free to contact us at contact@theclassicalyoga.com or +91 81096-96955</p>\n<p>See you at the program!</p>\n<p>Warm regards,<br />The Classical Yoga Team</p>"   

    , "\n<p><strong>* Angamardana | 18-22 Oct 2021 | Raipur, C.G. *</strong></p>\n<p>Greetings,<br />We are very excited to have you at the upcoming Angamardana program. Please find information you'll need below.</p>\n<p>Program Information:<br />🧘&zwj;♀️ Program Name: Angamardana<br />📅 Program Date: Oct 18-22<br />🕐 Timings: 6:00 AM - 8:15 AM <br />🧘&zwj;♂️ Age: 14 years and above<br />🏡 Venue: Rotary Greater Hall, Pagaria Complex<br />Bus Stand, Pandri, Raipur (https://bit.ly/3BSPMI5) <br /><br />Check in: 30 minutes before session starts</p>\n<p>Session starts everyday SHARP on time. It's best to be seated at least 5 minutes ahead of time and let your breath and metabolism settle down. Late comers may not be allowed to participate.</p>\n<p>General Information:<br />✔️ Ensure to wear face mask, maintain social distancing, and take care of hand hygiene and respiratory etiquette at all times</p>\n<p>✔️ Attendance for all sessions is required</p>\n<p>✔️ Wear loose fitting and comfortable clothing</p>\n<p>✔️ Bring a yoga mat or cloth-mat to sit on</p>\n<p>✔️ You can bring a cushion if needed to sit comfortably on the floor</p>\n<p>✔️ Please allow additional time of 10-15 minutes for traffic delays, find parking and complete check-in formalities before the program begins</p>\n<p>Empty stomach condition required: Due to the nature of the practices, please ensure you finish any heavy meal at least 4 hours before the class, snack 2.5 hours before and beverage (except water) at least 1.5 hour before the session.</p>\n<p>If you have any questions feel free to contact us at contact@theclassicalyoga.com or +91 81096-96955</p>\n<p>See you at the program!</p>\n<p>Warm regards,<br />The Classical Yoga Team</p>"   

    , "\n<p><strong>* Yogasanas | 11 Oct - 14 Oct & 16 Oct 2021 | Raipur, C.G. *</strong></p>\n<p>Greetings,<br />We are very excited to have you at the upcoming Yogasanas program. Please find information you'll need below.</p>\n<p>Program Information:<br />🧘&zwj;♀️ Program Name: Yogasanas<br />📅 Program Date: Oct 11-14 & 16<br />🕐 Timings: 6:00 AM - 8:15 AM <br />🧘&zwj;♂️ Age: 14 years and above<br />🏡 Venue: Rotary Greater Hall, Pagaria Complex<br />Bus Stand, Pandri, Raipur (https://bit.ly/3BSPMI5) <br /><br />Check in: 30 minutes before session starts</p>\n<p>Session starts everyday SHARP on time. It's best to be seated at least 5 minutes ahead of time and let your breath and metabolism settle down. Late comers may not be allowed to participate.</p>\n<p>General Information:<br />✔️ Ensure to wear face mask, maintain social distancing, and take care of hand hygiene and respiratory etiquette at all times</p>\n<p>✔️ Attendance for all sessions is required</p>\n<p>✔️ Wear loose fitting and comfortable clothing</p>\n<p>✔️ Bring a yoga mat or cloth-mat to sit on</p>\n<p>✔️ You can bring a cushion if needed to sit comfortably on the floor</p>\n<p>✔️ Please allow additional time of 10-15 minutes for traffic delays, find parking and complete check-in formalities before the program begins</p>\n<p>Empty stomach condition required: Due to the nature of the practices, please ensure you finish any heavy meal at least 4 hours before the class, snack 2.5 hours before and beverage (except water) at least 1.5 hour before the session.</p>\n<p>If you have any questions feel free to contact us at contact@theclassicalyoga.com or +91 81096-96955</p>\n<p>See you at the program!</p>\n<p>Warm regards,<br />The Classical Yoga Team</p>"  

    , "\n<p><strong>* Yoga For Depression | 11 Oct 2021 | Raipur, C.G. *</strong></p>\n<p>Greetings,<br />We are very excited to have you at the upcoming Yoga For Depression program. Please find information you'll need below.</p>\n<p>Program Information:<br />🧘&zwj;♀️ Program Name: Yoga For Depression<br />📅 Program Date: Oct 11<br />🕐 Timings: 8:30 AM - 9:30 AM <br />🧘&zwj;♂️ Age: 14 years and above<br />🏡 Venue: Rotary Greater Hall, Pagaria Complex<br />Bus Stand, Pandri, Raipur (https://bit.ly/3BSPMI5) <br /><br />Check in: 30 minutes before session starts</p>\n<p>Session starts everyday SHARP on time. It's best to be seated at least 5 minutes ahead of time and let your breath and metabolism settle down. Late comers may not be allowed to participate.</p>\n<p>General Information:<br />✔️ Ensure to wear face mask, maintain social distancing, and take care of hand hygiene and respiratory etiquette at all times</p>\n<p>✔️ It is advisable NOT to sit for the program with a full stomach or immediately after the meal. Somewhat hungry, light stomach or empty stomach is optimal.</p>\n<p>✔️ Wear loose fitting and comfortable clothing</p>\n<p>✔️ Bring a yoga mat or cloth-mat to sit on</p>\n<p>✔️ You can bring a cushion if needed to sit comfortably on the floor</p>\n<p>✔️ Please allow additional time of 10-15 minutes for traffic delays, find parking and complete check-in formalities before the program begins</p>If you have any questions feel free to contact us at contact@theclassicalyoga.com or +91 81096-96955</p>\n<p>See you at the program!</p>\n<p>Warm regards,<br />The Classical Yoga Team</p>"  

    , "\n<p><strong>* Upa Yoga (3 Day) | 25 - 27 Oct 2021 | Raipur, C.G. *</strong></p>\n<p>Greetings,<br />We are very excited to have you at the upcoming Upa Yoga (3 Day) program. Please find information you'll need below.</p>\n<p>Program Information:<br />🧘&zwj;♀️ Program Name: Upa Yoga (3 Day)<br />📅 Program Date: Oct 25-27<br />🕐 Timings: 7:00 AM - 8:00 AM <br />🧘&zwj;♂️ Age: 14 years and above<br />🏡 Venue: Rotary Greater Hall, Pagaria Complex<br />Bus Stand, Pandri, Raipur (https://bit.ly/3BSPMI5) <br /><br />Check in: 30 minutes before session starts</p>\n<p>Session starts everyday SHARP on time. It's best to be seated at least 5 minutes ahead of time and let your breath and metabolism settle down. Late comers may not be allowed to participate.</p>\n<p>General Information:<br />✔️ Ensure to wear face mask, maintain social distancing, and take care of hand hygiene and respiratory etiquette at all times</p>\n<p>✔️ It is advisable NOT to sit for the program with a full stomach or immediately after the meal. Somewhat hungry, light stomach or empty stomach is optimal.</p>\n<p>✔️ Wear loose fitting and comfortable clothing</p>\n<p>✔️ Bring a yoga mat or cloth-mat to sit on</p>\n<p>✔️ You can bring a cushion if needed to sit comfortably on the floor</p>\n<p>✔️ Please allow additional time of 10-15 minutes for traffic delays, find parking and complete check-in formalities before the program begins</p>If you have any questions feel free to contact us at contact@theclassicalyoga.com or +91 81096-96955</p>\n<p>See you at the program!</p>\n<p>Warm regards,<br />The Classical Yoga Team</p>"  

    , "\n<p><strong>* Upa Yoga (4 Day) | 25 - 28 Oct 2021 | Raipur, C.G. *</strong></p>\n<p>Greetings,<br />We are very excited to have you at the upcoming Upa Yoga (4 Day) program. Please find information you'll need below.</p>\n<p>Program Information:<br />🧘&zwj;♀️ Program Name: Upa Yoga (4 Day)<br />📅 Program Date: Oct 25-28<br />🕐 Timings: 7:00 AM - 8:00 AM <br />🧘&zwj;♂️ Age: 14 years and above<br />🏡 Venue: Rotary Greater Hall, Pagaria Complex<br />Bus Stand, Pandri, Raipur (https://bit.ly/3BSPMI5) <br /><br />Check in: 30 minutes before session starts</p>\n<p>Session starts everyday SHARP on time. It's best to be seated at least 5 minutes ahead of time and let your breath and metabolism settle down. Late comers may not be allowed to participate.</p>\n<p>General Information:<br />✔️ Ensure to wear face mask, maintain social distancing, and take care of hand hygiene and respiratory etiquette at all times</p>\n<p>✔️ It is advisable NOT to sit for the program with a full stomach or immediately after the meal. Somewhat hungry, light stomach or empty stomach is optimal.</p>\n<p>✔️ Wear loose fitting and comfortable clothing</p>\n<p>✔️ Bring a yoga mat or cloth-mat to sit on</p>\n<p>✔️ You can bring a cushion if needed to sit comfortably on the floor</p>\n<p>✔️ Please allow additional time of 10-15 minutes for traffic delays, find parking and complete check-in formalities before the program begins</p>If you have any questions feel free to contact us at contact@theclassicalyoga.com or +91 81096-96955</p>\n<p>See you at the program!</p>\n<p>Warm regards,<br />The Classical Yoga Team</p>"  

    , "\n<p><strong>* Upa Yoga (5 Day) | 25 - 29 Oct 2021 | Raipur, C.G. *</strong></p>\n<p>Greetings,<br />We are very excited to have you at the upcoming Upa Yoga (5 Day) program. Please find information you'll need below.</p>\n<p>Program Information:<br />🧘&zwj;♀️ Program Name: Upa Yoga (5 Day)<br />📅 Program Date: Oct 25-29<br />🕐 Timings: 7:00 AM - 8:00 AM <br />🧘&zwj;♂️ Age: 14 years and above<br />🏡 Venue: Rotary Greater Hall, Pagaria Complex<br />Bus Stand, Pandri, Raipur (https://bit.ly/3BSPMI5) <br /><br />Check in: 30 minutes before session starts</p>\n<p>Session starts everyday SHARP on time. It's best to be seated at least 5 minutes ahead of time and let your breath and metabolism settle down. Late comers may not be allowed to participate.</p>\n<p>General Information:<br />✔️ Ensure to wear face mask, maintain social distancing, and take care of hand hygiene and respiratory etiquette at all times</p>\n<p>✔️ It is advisable NOT to sit for the program with a full stomach or immediately after the meal. Somewhat hungry, light stomach or empty stomach is optimal.</p>\n<p>✔️ Wear loose fitting and comfortable clothing</p>\n<p>✔️ Bring a yoga mat or cloth-mat to sit on</p>\n<p>✔️ You can bring a cushion if needed to sit comfortably on the floor</p>\n<p>✔️ Please allow additional time of 10-15 minutes for traffic delays, find parking and complete check-in formalities before the program begins</p>If you have any questions feel free to contact us at contact@theclassicalyoga.com or +91 81096-96955</p>\n<p>See you at the program!</p>\n<p>Warm regards,<br />The Classical Yoga Team</p>" 
] ;

const bodyEve = [
      "\n<p><strong>* Daily Guided Yoga | 1 - 31 Oct 2021 | Raipur, C.G. *</strong></p>\n\n<p>Greetings,</p>\n\n<p><br />We are very excited to have you at the upcoming <strong>Daily Guided Yoga</strong> program. Please find information you'll need below.</p>\n\n<p><strong>Program Information:</strong><br />🧘&zwj;♀️ Program Name: Daily Guided Yoga<br />📅 Program Date: Oct 1 - 31<br />🕐 Timings: 5:00 PM - 6:00 PM [<b>Exception</b> - For 4, 5 & 6 Oct timings will be from 5:00 PM - 6:30 PM]<br />🕐 Timings: ProgramTiming<br />🧘&zwj;♂️ Age: 14 years and above<br />🏡 Venue: Rotary Greater Hall, Pagaria Complex, Bus Stand, Pandri, Raipur (https://bit.ly/3BSPMI5)<br /><br />Check in: 30 minutes before session starts</p>\n\n<p>Session starts everyday <strong>SHARP</strong> on time. It's best to be seated at least 5 minutes ahead of time and let your breath and metabolism settle down. Late comers may not be allowed to participate.</p>\n\n<p><strong>General Information:</strong><br />✔️ Ensure to wear face mask, maintain social distancing, and take care of hand hygiene and respiratory etiquette at all times</p>\n\n<p>✔️ Attendance for all sessions is required</p>\n\n<p>✔️ Wear loose fitting and comfortable clothing</p>\n\n<p>✔️ Bring a yoga mat or cloth-mat to sit on</p>\n\n<p>✔️ You can bring a cushion if needed to sit comfortably on the floor</p>\n\n<p>✔️ Please allow additional time of 10-15 minutes for traffic delays, find parking and complete check-in formalities before the program begins</p>\n\n<p><span style='background-color: #ffff00;'><strong>Empty stomach condition required:</strong></span> Due to the nature of the practices, please ensure you finish any heavy meal at least 4 hours before the class, snack 2.5 hours before and beverage (except water) at least 1.5 hour before the session.</p>\n\n<p>If you have any questions feel free to contact us at <strong>contact@theclassicalyoga.com</strong> or <strong>+91 81096-96955</strong></p>\n\n<p>See you at the program!</p>\n\n<p>Warm regards,<br />The Classical Yoga Team</p>"

    , "\n<p><strong>* Bhuta Shuddhi | 8 Oct 2021 | Raipur, C.G. *</strong></p>\n<p>Greetings,<br />We are very excited to have you at the upcoming Bhuta Shuddhi program. Please find information you'll need below.</p>\n<p>Program Information:<br />🧘&zwj;♀️ Program Name: Bhuta Shuddhi<br />📅 Program Date: Oct 8<br />🕐 Timings: 7:00 PM - 8:00 PM <br />🧘&zwj;♂️ Age: 14 years and above<br />🏡 Venue: Rotary Greater Hall, Pagaria Complex<br />Bus Stand, Pandri, Raipur (https://bit.ly/3BSPMI5) <br /><br />Check in: 30 minutes before session starts</p>\n<p>Session starts everyday SHARP on time. It's best to be seated at least 5 minutes ahead of time and let your breath and metabolism settle down. Late comers may not be allowed to participate.</p>\n<p>General Information:<br />✔️ Ensure to wear face mask, maintain social distancing, and take care of hand hygiene and respiratory etiquette at all times</p>\n<p>✔️ Attendance for all sessions is required</p>\n<p>✔️ Wear loose fitting and comfortable clothing</p>\n<p>✔️ Bring a yoga mat or cloth-mat to sit on</p>\n<p>✔️ You can bring a cushion if needed to sit comfortably on the floor</p>\n<p>✔️ Please allow additional time of 10-15 minutes for traffic delays, find parking and complete check-in formalities before the program begins</p>\n<p>Empty stomach condition required: Due to the nature of the practices, please ensure you finish any heavy meal at least 4 hours before the class, snack 2.5 hours before and beverage (except water) at least 1.5 hour before the session.</p>\n<p>If you have any questions feel free to contact us at contact@theclassicalyoga.com or +91 81096-96955</p>\n<p>See you at the program!</p>\n<p>Warm regards,<br />The Classical Yoga Team</p>" 

    , "\n<p><strong>* Surya Kriya (For those who have completed Surya Shakti) | 7 Oct 2021 | Raipur, C.G. *</strong></p>\n<p>Greetings,<br />We are very excited to have you at the upcoming Surya Kriya program. Please find information you'll need below.</p>\n<p>Program Information:<br />🧘&zwj;♀️ Program Name: Surya Kriya (For those who have completed Surya Shakti)<br />📅 Program Date: Oct 7<br />🕐 Timings: 6:30 PM - 8:30 PM <br />🧘&zwj;♂️ Age: 14 years and above<br />🏡 Venue: Rotary Greater Hall, Pagaria Complex<br />Bus Stand, Pandri, Raipur (https://bit.ly/3BSPMI5) <br /><br />Check in: 30 minutes before session starts</p>\n<p>Session starts everyday SHARP on time. It's best to be seated at least 5 minutes ahead of time and let your breath and metabolism settle down. Late comers may not be allowed to participate.</p>\n<p>General Information:<br />✔️ Ensure to wear face mask, maintain social distancing, and take care of hand hygiene and respiratory etiquette at all times</p>\n<p>✔️ Attendance for all sessions is required</p>\n<p>✔️ Wear loose fitting and comfortable clothing</p>\n<p>✔️ Bring a yoga mat or cloth-mat to sit on</p>\n<p>✔️ You can bring a cushion if needed to sit comfortably on the floor</p>\n<p>✔️ Please allow additional time of 10-15 minutes for traffic delays, find parking and complete check-in formalities before the program begins</p>\n<p>Empty stomach condition required: Due to the nature of the practices, please ensure you finish any heavy meal at least 4 hours before the class, snack 2.5 hours before and beverage (except water) at least 1.5 hour before the session.</p>\n<p>If you have any questions feel free to contact us at contact@theclassicalyoga.com or +91 81096-96955</p>\n<p>See you at the program!</p>\n<p>Warm regards,<br />The Classical Yoga Team</p>"  

    , "\n<p><strong>* Surya Shakti | 4-6 Oct 2021 | Raipur, C.G. *</strong></p>\n<p>Greetings,<br />We are very excited to have you at the upcoming Surya Shakti program. Please find information you'll need below.</p>\n<p>Program Information:<br />🧘&zwj;♀️ Program Name: Surya Shakti<br />📅 Program Date: Oct 4-6<br />🕐 Timings: 5:00 PM - 6:30 PM <br />🧘&zwj;♂️ Age: 14 years and above<br />🏡 Venue: Rotary Greater Hall, Pagaria Complex<br />Bus Stand, Pandri, Raipur (https://bit.ly/3BSPMI5) <br /><br />Check in: 30 minutes before session starts</p>\n<p>Session starts everyday SHARP on time. It's best to be seated at least 5 minutes ahead of time and let your breath and metabolism settle down. Late comers may not be allowed to participate.</p>\n<p>General Information:<br />✔️ Ensure to wear face mask, maintain social distancing, and take care of hand hygiene and respiratory etiquette at all times</p>\n<p>✔️ Attendance for all sessions is required</p>\n<p>✔️ Wear loose fitting and comfortable clothing</p>\n<p>✔️ Bring a yoga mat or cloth-mat to sit on</p>\n<p>✔️ You can bring a cushion if needed to sit comfortably on the floor</p>\n<p>✔️ Please allow additional time of 10-15 minutes for traffic delays, find parking and complete check-in formalities before the program begins</p>\n<p>Empty stomach condition required: Due to the nature of the practices, please ensure you finish any heavy meal at least 4 hours before the class, snack 2.5 hours before and beverage (except water) at least 1.5 hour before the session.</p>\n<p>If you have any questions feel free to contact us at contact@theclassicalyoga.com or +91 81096-96955</p>\n<p>See you at the program!</p>\n<p>Warm regards,<br />The Classical Yoga Team</p>" 

    , "\n<p><strong>* Angamardana | 18-22 Oct 2021 | Raipur, C.G. *</strong></p>\n<p>Greetings,<br />We are very excited to have you at the upcoming Angamardana program. Please find information you'll need below.</p>\n<p>Program Information:<br />🧘&zwj;♀️ Program Name: Angamardana<br />📅 Program Date: Oct 18-22<br />🕐 Timings: 6:15 PM - 8:30 PM <br />🧘&zwj;♂️ Age: 14 years and above<br />🏡 Venue: Rotary Greater Hall, Pagaria Complex<br />Bus Stand, Pandri, Raipur (https://bit.ly/3BSPMI5) <br /><br />Check in: 30 minutes before session starts</p>\n<p>Session starts everyday SHARP on time. It's best to be seated at least 5 minutes ahead of time and let your breath and metabolism settle down. Late comers may not be allowed to participate.</p>\n<p>General Information:<br />✔️ Ensure to wear face mask, maintain social distancing, and take care of hand hygiene and respiratory etiquette at all times</p>\n<p>✔️ Attendance for all sessions is required</p>\n<p>✔️ Wear loose fitting and comfortable clothing</p>\n<p>✔️ Bring a yoga mat or cloth-mat to sit on</p>\n<p>✔️ You can bring a cushion if needed to sit comfortably on the floor</p>\n<p>✔️ Please allow additional time of 10-15 minutes for traffic delays, find parking and complete check-in formalities before the program begins</p>\n<p>Empty stomach condition required: Due to the nature of the practices, please ensure you finish any heavy meal at least 4 hours before the class, snack 2.5 hours before and beverage (except water) at least 1.5 hour before the session.</p>\n<p>If you have any questions feel free to contact us at contact@theclassicalyoga.com or +91 81096-96955</p>\n<p>See you at the program!</p>\n<p>Warm regards,<br />The Classical Yoga Team</p>"   

    , "\n<p><strong>* Yogasanas | 11 Oct - 14 Oct & 16 Oct 2021 | Raipur, C.G. *</strong></p>\n<p>Greetings,<br />We are very excited to have you at the upcoming Yogasanas program. Please find information you'll need below.</p>\n<p>Program Information:<br />🧘&zwj;♀️ Program Name: Yogasanas<br />📅 Program Date: Oct 11-14 & 16<br />🕐 Timings: 6:15 PM - 8:30 PM <br />🧘&zwj;♂️ Age: 14 years and above<br />🏡 Venue: Rotary Greater Hall, Pagaria Complex<br />Bus Stand, Pandri, Raipur (https://bit.ly/3BSPMI5) <br /><br />Check in: 30 minutes before session starts</p>\n<p>Session starts everyday SHARP on time. It's best to be seated at least 5 minutes ahead of time and let your breath and metabolism settle down. Late comers may not be allowed to participate.</p>\n<p>General Information:<br />✔️ Ensure to wear face mask, maintain social distancing, and take care of hand hygiene and respiratory etiquette at all times</p>\n<p>✔️ Attendance for all sessions is required</p>\n<p>✔️ Wear loose fitting and comfortable clothing</p>\n<p>✔️ Bring a yoga mat or cloth-mat to sit on</p>\n<p>✔️ You can bring a cushion if needed to sit comfortably on the floor</p>\n<p>✔️ Please allow additional time of 10-15 minutes for traffic delays, find parking and complete check-in formalities before the program begins</p>\n<p>Empty stomach condition required: Due to the nature of the practices, please ensure you finish any heavy meal at least 4 hours before the class, snack 2.5 hours before and beverage (except water) at least 1.5 hour before the session.</p>\n<p>If you have any questions feel free to contact us at contact@theclassicalyoga.com or +91 81096-96955</p>\n<p>See you at the program!</p>\n<p>Warm regards,<br />The Classical Yoga Team</p>"   

    , "\n<p><strong>* Yoga For Depression | 11 Oct 2021 | Raipur, C.G. *</strong></p>\n<p>Greetings,<br />We are very excited to have you at the upcoming Yoga For Depression program. Please find information you'll need below.</p>\n<p>Program Information:<br />🧘&zwj;♀️ Program Name: Yoga For Depression<br />📅 Program Date: Oct 11<br />🕐 Timings: 5:00 PM - 6:00 PM <br />🧘&zwj;♂️ Age: 14 years and above<br />🏡 Venue: Rotary Greater Hall, Pagaria Complex<br />Bus Stand, Pandri, Raipur (https://bit.ly/3BSPMI5) <br /><br />Check in: 30 minutes before session starts</p>\n<p>Session starts everyday SHARP on time. It's best to be seated at least 5 minutes ahead of time and let your breath and metabolism settle down. Late comers may not be allowed to participate.</p>\n<p>General Information:<br />✔️ Ensure to wear face mask, maintain social distancing, and take care of hand hygiene and respiratory etiquette at all times</p>\n<p>✔️ It is advisable NOT to sit for the program with a full stomach or immediately after the meal. Somewhat hungry, light stomach or empty stomach is optimal.</p>\n<p>✔️ Wear loose fitting and comfortable clothing</p>\n<p>✔️ Bring a yoga mat or cloth-mat to sit on</p>\n<p>✔️ You can bring a cushion if needed to sit comfortably on the floor</p>\n<p>✔️ Please allow additional time of 10-15 minutes for traffic delays, find parking and complete check-in formalities before the program begins</p>If you have any questions feel free to contact us at contact@theclassicalyoga.com or +91 81096-96955</p>\n<p>See you at the program!</p>\n<p>Warm regards,<br />The Classical Yoga Team</p>"   

    , "\n<p><strong>* Upa Yoga (3 Day) | 25 - 27 Oct 2021 | Raipur, C.G. *</strong></p>\n<p>Greetings,<br />We are very excited to have you at the upcoming Upa Yoga (3 Day) program. Please find information you'll need below.</p>\n<p>Program Information:<br />🧘&zwj;♀️ Program Name: Upa Yoga (3 Day)<br />📅 Program Date: Oct 25-27<br />🕐 Timings: 6:30 PM - 7:30 PM <br />🧘&zwj;♂️ Age: 14 years and above<br />🏡 Venue: Rotary Greater Hall, Pagaria Complex<br />Bus Stand, Pandri, Raipur (https://bit.ly/3BSPMI5) <br /><br />Check in: 30 minutes before session starts</p>\n<p>Session starts everyday SHARP on time. It's best to be seated at least 5 minutes ahead of time and let your breath and metabolism settle down. Late comers may not be allowed to participate.</p>\n<p>General Information:<br />✔️ Ensure to wear face mask, maintain social distancing, and take care of hand hygiene and respiratory etiquette at all times</p>\n<p>✔️ It is advisable NOT to sit for the program with a full stomach or immediately after the meal. Somewhat hungry, light stomach or empty stomach is optimal.</p>\n<p>✔️ Wear loose fitting and comfortable clothing</p>\n<p>✔️ Bring a yoga mat or cloth-mat to sit on</p>\n<p>✔️ You can bring a cushion if needed to sit comfortably on the floor</p>\n<p>✔️ Please allow additional time of 10-15 minutes for traffic delays, find parking and complete check-in formalities before the program begins</p>If you have any questions feel free to contact us at contact@theclassicalyoga.com or +91 81096-96955</p>\n<p>See you at the program!</p>\n<p>Warm regards,<br />The Classical Yoga Team</p>"  

    , "\n<p><strong>* Upa Yoga (4 Day) | 25 - 28 Oct 2021 | Raipur, C.G. *</strong></p>\n<p>Greetings,<br />We are very excited to have you at the upcoming Upa Yoga (4 Day) program. Please find information you'll need below.</p>\n<p>Program Information:<br />🧘&zwj;♀️ Program Name: Upa Yoga (4 Day)<br />📅 Program Date: Oct 25-28<br />🕐 Timings: 6:30 PM - 7:30 PM <br />🧘&zwj;♂️ Age: 14 years and above<br />🏡 Venue: Rotary Greater Hall, Pagaria Complex<br />Bus Stand, Pandri, Raipur (https://bit.ly/3BSPMI5) <br /><br />Check in: 30 minutes before session starts</p>\n<p>Session starts everyday SHARP on time. It's best to be seated at least 5 minutes ahead of time and let your breath and metabolism settle down. Late comers may not be allowed to participate.</p>\n<p>General Information:<br />✔️ Ensure to wear face mask, maintain social distancing, and take care of hand hygiene and respiratory etiquette at all times</p>\n<p>✔️ It is advisable NOT to sit for the program with a full stomach or immediately after the meal. Somewhat hungry, light stomach or empty stomach is optimal.</p>\n<p>✔️ Wear loose fitting and comfortable clothing</p>\n<p>✔️ Bring a yoga mat or cloth-mat to sit on</p>\n<p>✔️ You can bring a cushion if needed to sit comfortably on the floor</p>\n<p>✔️ Please allow additional time of 10-15 minutes for traffic delays, find parking and complete check-in formalities before the program begins</p>If you have any questions feel free to contact us at contact@theclassicalyoga.com or +91 81096-96955</p>\n<p>See you at the program!</p>\n<p>Warm regards,<br />The Classical Yoga Team</p>" 

    , "\n<p><strong>* Upa Yoga (5 Day) | 25 - 29 Oct 2021 | Raipur, C.G. *</strong></p>\n<p>Greetings,<br />We are very excited to have you at the upcoming Upa Yoga (5 Day) program. Please find information you'll need below.</p>\n<p>Program Information:<br />🧘&zwj;♀️ Program Name: Upa Yoga (5 Day)<br />📅 Program Date: Oct 25-29<br />🕐 Timings: 6:30 PM - 7:30 PM <br />🧘&zwj;♂️ Age: 14 years and above<br />🏡 Venue: Rotary Greater Hall, Pagaria Complex<br />Bus Stand, Pandri, Raipur (https://bit.ly/3BSPMI5) <br /><br />Check in: 30 minutes before session starts</p>\n<p>Session starts everyday SHARP on time. It's best to be seated at least 5 minutes ahead of time and let your breath and metabolism settle down. Late comers may not be allowed to participate.</p>\n<p>General Information:<br />✔️ Ensure to wear face mask, maintain social distancing, and take care of hand hygiene and respiratory etiquette at all times</p>\n<p>✔️ It is advisable NOT to sit for the program with a full stomach or immediately after the meal. Somewhat hungry, light stomach or empty stomach is optimal.</p>\n<p>✔️ Wear loose fitting and comfortable clothing</p>\n<p>✔️ Bring a yoga mat or cloth-mat to sit on</p>\n<p>✔️ You can bring a cushion if needed to sit comfortably on the floor</p>\n<p>✔️ Please allow additional time of 10-15 minutes for traffic delays, find parking and complete check-in formalities before the program begins</p>If you have any questions feel free to contact us at contact@theclassicalyoga.com or +91 81096-96955</p>\n<p>See you at the program!</p>\n<p>Warm regards,<br />The Classical Yoga Team</p>"  

    , "\n<p><strong>* Free Yoga Day | 1 Oct 2021 | Raipur, C.G. *</strong></p>\n<p>Greetings,<br />We are very excited to have you at the upcoming Free Yoga Day program. Please find information you'll need below.</p>\n<p>Program Information:<br />🧘&zwj;♀️ Program Name: Free Yoga Day<br />📅 Program Date: Oct 1<br />🕐 Timings: 5:00 PM - 6:00 PM <br />🧘&zwj;♂️ Age: 14 years and above<br />🏡 Venue: Rotary Greater Hall, Pagaria Complex<br />Bus Stand, Pandri, Raipur (https://bit.ly/3BSPMI5) <br /><br />Check in: 30 minutes before session starts</p>\n<p>Session starts everyday SHARP on time. It's best to be seated at least 5 minutes ahead of time and let your breath and metabolism settle down. Late comers may not be allowed to participate.</p>\n<p>General Information:<br />✔️ Ensure to wear face mask, maintain social distancing, and take care of hand hygiene and respiratory etiquette at all times</p>\n<p>✔️ It is advisable NOT to sit for the program with a full stomach or immediately after the meal. Somewhat hungry, light stomach or empty stomach is optimal.</p>\n<p>✔️ Wear loose fitting and comfortable clothing</p>\n<p>✔️ Bring a yoga mat or cloth-mat to sit on</p>\n<p>✔️ You can bring a cushion if needed to sit comfortably on the floor</p>\n<p>✔️ Please allow additional time of 10-15 minutes for traffic delays, find parking and complete check-in formalities before the program begins</p>If you have any questions feel free to contact us at contact@theclassicalyoga.com or +91 81096-96955</p>\n<p>See you at the program!</p>\n<p>Warm regards,<br />The Classical Yoga Team</p>"   
] ;

function getBody(program, time){
    var body;
    if(time.includes("am") || time.includes("AM") || time.includes("सुबह")){
        body = bodyMor;
    } else {
        body = bodyEve;
    }
    for (var i = 0; i < body.length; i++) {
        var bodyItem = body[i];
        if(bodyItem.includes(program)){
            //console.log(bodyItem);
            return bodyItem;
        }
    }
    return "NA";
}

function sendEmail(to,program, time) {
    //alert(to);
    Email.send({
      Host: "smtpout.secureserver.net",
      Username: "contact@theclassicalyoga.com",
      Password: "br12345678",
      To: to,
      From: "contact@theclassicalyoga.com",
      Subject: "Program Guidelines and Confirmation for "+ program,
      Body: getBody(program, time)
    })
    .then(function (message) {
        console.log("Mail sent successfully")
    });
  }

  
  
